name: Merge main branch with develop

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  merge:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Merge Main into Develop
        run: |
          git checkout develop
          git merge main --no-edit
          git push origin develop
